export default function confirmation() {
    return (
      <div className="confirmation">
        <div className="rectangle-1">
        </div>
        <div className="appointment-confirmation">
          APPOINTMENT CONFIRMATION
        </div>
        <div className="full-logo">
          <div className="ohospital-logo">
            <div className="ellipse-1">
            </div>
            <div className="container-6">
              <div className="ellipse-4">
              </div>
              <img className="ellipse-3" />
            </div>
          </div>
          <span className="ohospital">
            OHospital
          </span>
        </div>
        <div className="container-4">
          <div className="arrow-left-solid-1">
            <img className="vector-3" />
          </div>
          <span className="appointment-confirmation-1">
            Appointment confirmation
          </span>
        </div>
        <p className="you-are-all-set-for-your-appointment-with-dr-lucas-mutua">
          <span className="you-are-all-set-for-your-appointment-with-dr-lucas-mutua-sub-19"></span><span></span>
        </p>
        <div className="container-9">
          <div className="container-8">
            <div className="calendar-check-regular-1">
              <img className="vector" />
            </div>
          </div>
          <div className="container">
            <div className="date-time">
              Date &amp; Time
            </div>
            <span className="april-26-th-2024-from-900930-am">
              April 26th, 2024 from 9.00 - 9.30am
            </span>
          </div>
        </div>
        <div className="container-7">
          <div className="container-10">
            <div className="location-dot-solid-1">
              <img className="vector-2" />
            </div>
          </div>
          <div className="container-5">
            <div className="location">
              Location
            </div>
            <span className="virtual-meeting-link">
              Virtual meeting link
            </span>
          </div>
        </div>
        <div className="frame-1">
          <span className="manage-appointment">
            Manage appointment
          </span>
        </div>
        <span className="this-is-an-electronic-consultation-ticket-generated-by-your-doctor-if-you-have-any-questions-please-contact-your-doctor">
          This is an electronic consultation ticket generated by your doctor. If you have any questions, please contact your doctor.
        </span>
        <span className="together-we-make-better-healthcare-possible">
          Together, we make better healthcare possible. 
        </span>
      </div>
    )
  }